name: sse_client
description: >-
  Provides client and server functionality for setting up bi-directional
  communication through Server Sent Events (SSE) and corresponding POST
  requests.
version: 0.0.1
homepage: https://www.github.com/jamiewest/sse_client
author: jamiewest.dev

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  uuid: ^2.0.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
